spring:
  application:
    name: api-gateway
  datasource:
    username: ${DB_AUTH_USERNAME}
    url: ${SQL_URI}
    password: ${DB_AUTH_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - DELETE
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-MICROSERVICE/
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<path>.*), /api/v1/$\{path}

        - id: USER-SERVICE
          uri: lb://USER-MICROSERVICE/
          predicates:
            - Path=/api/v1/user/**
          filters:
            - RewritePath=/api/v1/user/(?<path>.*), /api/v1/$\{path}

        - id: RIDE-SERVICE
          uri: lb://RIDE-MICROSERVICE/
          predicates:
            - Path=/api/v1/ride/**
          filters:
            - RewritePath=/api/v1/ride/(?<path>.*), /api/v1/ride$\{path}

        - id: IMAGE-SERVICE
          uri: lb://IMAGE-MICROSERVICE/
          predicates:
            - Path=/api/v1/image/**
          filters:
            - RewritePath=/api/v1/image/(?<path>.*), /api/v1/email$\{path}
allowed:
  origin: "*"
jwt:
  secret:
    jws: ${JWS_SECRET_KEY}
server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: ${EUREKA_URI}