spring:
  application:
    name: api-gateway
  datasource:
    username: ${DB_AUTH_USERNAME}
    url: ${SQL_URI}
    password: ${DB_AUTH_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - DELETE
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-MICROSERVICE/
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<path>.*), /api/$\{path}
server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: ${EUREKA_URI}