spring:
  application:
    name: auth-microservice
  datasource:
    username: ${DB_AUTH_USERNAME}
    url: ${SQL_URI}
    password: ${DB_AUTH_PASSWORD}
    driver-class-name: org.postgresql.Driver
jwt:
  secret:
    jwe: ${JWE_SECRET_KEY}
    jws: ${JWS_SECRET_KEY}
server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: ${EUREKA_URI}