spring:
  application:
    name: auth-microservice
  redis: 
    host: redis
    port: 6379
server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: ${EUREKA_URI}