spring:
  application:
    name: auth-microservice
  datasource:
    username: ${DB_USERNAME_AUTH_MICROSERVICE}
    url: ${SQL_URI}
    password: ${DB_PASSWORD_AUTH_MICROSERVICE}
    driver-class-name: org.postgresql.Driver
server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: ${EUREKA_URI}