spring:
  application:
    name: ride-microservice
  datasource:
    username: ${DB_USERNAME_RIDE_MICROSERVICE}
    url: ${SQL_URI}
    password: ${DB_PASSWORD_RIDE_MICROSERVICE}
server:
  port: 8080
kafka:
  bootstrap-servers: ${KAFKA_URI}
  producer:
    rating-topic:
      partitions: 3
      replicas: 1
      name: rating-message-topic
    trip-topic:
      partitions: 3
      replicas: 1
      name: trip-message-topic
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: ${EUREKA_URI}