spring:
  application:
    name: user-microservice
  datasource:
    username: ${DB_USERNAME_USER_MICROSERVICE}
    url: ${SQL_URI}
    password: ${DB_PASSWORD_USER_MICROSERVICE}
server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: ${EUREKA_URI}