spring:
  application:
    name: user-microservice
  datasource:
    username: ${DB_USERNAME_USER_MICROSERVICE}
    url: ${SQL_URI}
    password: ${DB_PASSWORD_USER_MICROSERVICE}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
  data:
    redis:
      host: ${REDIS_URI}
      post: ${REDIS_PORT}
server:
  port: 8080
kafka:
  bootstrap-servers: ${KAFKA_URI}
  consumer:
    consumer-thread-num: 3
    user-topic:
      consumer-group-id: user-microservice-user-group
      name: user-message-topic
    rating-topic:
      consumer-group-id: user-microservice-rating-group
      name: rating-message-topic
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: ${EUREKA_URI}