spring:
  application:
    name: user-microservice
  datasource:
    username: ${SQL_USERNAME}
    url: ${SQL_URI}
    password: ${SQL_PASSWORD}
server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: ${EUREKA_URI}